AWSTemplateFormatVersion: 2010-09-09

Parameters:
    CodeDeployRole:
        Type: String

Resources:
    WebappApplication:
        Type: AWS::CodeDeploy::Application
        Properties:
            ApplicationName: CodeDeployAppNameWithASG
    WebappDeploymentGroup:
        Type: AWS::CodeDeploy::DeploymentGroup
        Properties:
            ApplicationName: !Ref WebappApplication
            ServiceRoleArn: !Ref CodeDeployRole
            DeploymentConfigName: CodeDeployDefault.OneAtATime
            DeploymentGroupName: CodeDeployGroupName
            AutoRollbackConfiguration:
                Enabled: true
                Events:
                    - DEPLOYMENT_FAILURE
                    - DEPLOYMENT_STOP_ON_REQUEST
Outputs:
    DeploymentGroup:
        Description: Webapp Deployment Group
        Value: !Ref WebappDeploymentGroup

    ApplicationName:
        Description: CodeDeploy Application name
        Value: !Ref WebappApplication
