AWSTemplateFormatVersion: 2010-09-09
Description: 'Cloudformation for provisioning services required to setup the CI/CD using GitHub actions and CodeDeploy'
Metadata:
    AWS::CloudFormation::Interface:
        ParameterGroups:
            - Label:
                  default: 'Github configurations'
              Parameters:
                  - GithubRepoName
                  - ThumbprintList
            - Label:
                  default: 'Instance Configurations'
              Parameters:
                  - ImageId
                  - InstanceType
                  - DomainAPI
                  - KeyPairName

Parameters:
    ThumbprintList:
        Type: String
        Default: 6938fd4d98bab03faadb97b34396831e3780aea1
        Description: A thumbprint of an Open ID Connector is a SHA1 hash of the public certificate of the host

    GithubRepoName:
        Type: String
        Default: mundobox/DEVOLTA-API
        Description: GitHub repository name Ex-TestUser/TestCodeDeploy

    ImageId:
        Type: 'AWS::EC2::Image::Id'
        Default: 'ami-08d4ac5b634553e16'
        Description: The Ubuntu 20.04 64 Bits (x86).

    InstanceType:
        Type: String
        Default: t3.small
        Description: The type of Amazon EC2 Linux instances that will be launched for this project.

    DomainAPI:
        Type: String
        Default: api.domain.gux.cl
        Description: Domain api for config nginx

    KeyPairName:
        Type: String
        Default: aws-key-pair-us-east-1-devolta
        Description: Name From Key Pair

Resources:
    Roles:
        Type: 'AWS::CloudFormation::Stack'
        Properties:
            TemplateURL: https://cf-templates-o39246gwf1cp-us-east-1.s3.amazonaws.com/roles.yaml
            Parameters:
                ThumbprintList: !Ref ThumbprintList
                GithubRepoName: !Ref GithubRepoName
    Instance:
        Type: 'AWS::CloudFormation::Stack'
        DependsOn: Roles
        Properties:
            TemplateURL: https://cf-templates-o39246gwf1cp-us-east-1.s3.amazonaws.com/instance.yml
            Parameters:
                ImageId: !Ref ImageId
                InstanceType: !Ref InstanceType
                DomainAPI: !Ref DomainAPI
                KeyPairName: !Ref KeyPairName
                WebappRole: !GetAtt Roles.Outputs.WebappRoleArn
                AWSRegion: !Ref 'AWS::Region'
    #CodeDeploy:
    #    Type: 'AWS::CloudFormation::Stack'
    #    DependsOn: Instance
    #    Properties:
    #        TemplateURL: https://cf-templates-9cotybvrduqa-us-east-1.s3.amazonaws.com/codeDeploy.yml
    #        Parameters:
    #            CodeDeployRole: !GetAtt Roles.Outputs.CodeDeployRoleArn
